-- Table SCRIPT_SET
CREATE TABLE SCRIPT_SET (
    MODULE VARCHAR(50),
    KEY VARCHAR(50),
    VALUE VARCHAR(20)
);
CREATE UNIQUE INDEX SCRIPT_SET_MODULE_IDX ON SCRIPT_SET ("MODULE","KEY");

-- Table GAME_GUNDEON
CREATE TABLE GAME_GUNDEON (
	GUNDEON_NAME VARCHAR(20),
	CONFIG_KEY VARCHAR(50),
	SORT INTEGER
);

INSERT INTO GAME_GUNDEON (GUNDEON_NAME, CONFIG_KEY, SORT) VALUES('羡鱼港', 'game.dungeon.xian-yu', 1);
INSERT INTO GAME_GUNDEON (GUNDEON_NAME, CONFIG_KEY, SORT) VALUES('万劫山庄', 'game.dungeon.wan-jie', 2);
INSERT INTO GAME_GUNDEON (GUNDEON_NAME, CONFIG_KEY, SORT) VALUES('无人谷', 'game.dungeon.wu-ren', 3);
INSERT INTO GAME_GUNDEON (GUNDEON_NAME, CONFIG_KEY, SORT) VALUES('明月山庄', 'game.dungeon.ming-yue', 4);
INSERT INTO GAME_GUNDEON (GUNDEON_NAME, CONFIG_KEY, SORT) VALUES('落日马场', 'game.dungeon.luo-ri', 5);
INSERT INTO GAME_GUNDEON (GUNDEON_NAME, CONFIG_KEY, SORT) VALUES('铁衣堡', 'game.dungeon.tie-yi', 6);
INSERT INTO GAME_GUNDEON (GUNDEON_NAME, CONFIG_KEY, SORT) VALUES('桃花源', 'game.dungeon.tao-hua', 7);
INSERT INTO GAME_GUNDEON (GUNDEON_NAME, CONFIG_KEY, SORT) VALUES('阴阳流', 'game.dungeon.yin-yang', 8);
INSERT INTO GAME_GUNDEON (GUNDEON_NAME, CONFIG_KEY, SORT) VALUES('北蛮铁塞', 'game.dungeon.bei-man', 9);


